const RC = require('rc')('CDIR', require('../../config/default.json'))

module.exports = {
  HOSTNAME: RC.HOSTNAME.replace(/\/$/, ''),
  DATABASE_URI: RC.DATABASE_URI,
  PORT: RC.PORT,
  END_USER_REGISTRY_URL: RC.END_USER_REGISTRY_URL,
  ENABLE_TOKEN_AUTH: RC.ENABLE_TOKEN_AUTH,
  TOKEN_EXPIRATION: RC.TOKEN_EXPIRATION,
  SCHEME_ID: RC.SCHEME_ID,
  DEFAULT_DFSP: RC.DEFAULT_DFSP,
  ADMIN_KEY: RC.ADMIN_KEY,
  ADMIN_SECRET: RC.ADMIN_SECRET,
  PATHFINDER: RC.PATHFINDER
}
